name: deploy_develop_workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true 
        default: ''
        type: string
env:
  MAJORVERSION: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Version
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Get version from input
      run: echo "VERSION=${GITHUB_BRANCH}" >> $GITHUB_ENV
      env: 
        GITHUB_BRANCH: ${{ github.event.inputs.version }}
    - name: Display version install
      run: echo "Installing dev version ${VERSION}"

    - run: npm install
    - run: npm rebuild
    - run: npm run-script build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: 'AKIAWXY7DGWYB5GTWUX5'
        aws-secret-access-key: ${{ secrets.AWS_TOOLKIT_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Deploy toolbox to S3 bucket
      run: aws s3 sync ./dist/ s3://s3robust-dev.toolkit.illinois.edu/content/$VERSION --delete --acl bucket-owner-full-control
    - run: npm run-script create-test-html -- --pathprefix='/$VERSION/examples/'
    - name: Deploy examples to S3 bucket
      run: aws s3 sync ./var/full-site-deploy/ s3://s3robust-dev.toolkit.illinois.edu/content/$VERSION/examples --delete --acl bucket-owner-full-control
    - name: Deploy static images in examples to S3 bucket
      run: aws s3 sync ./tests/_reference/ s3://s3robust-dev.toolkit.illinois.edu/content/$VERSION/examples/static-images --acl bucket-owner-full-control
    - name: Invalidate Cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id E3EJ8O9WXGDQCO --paths "/$VERSION*"
