module.exports = [
    {
        "name": "Illini Orange",
        "var": "il-orange",
        "pms": "2026C",
        "cmyk": "0/80/90/0",
        "rgb": "255/85/46",
        "hex": "#FF552E",
        "variants": [
            {
                "name": "Altgeld",
                "hex": "#DD3403",
                "var": "il-altgeld",
            },
        ],
    },
    {
        "name": "Illini Blue",
        "var": "il-blue",
        "pms": "2767",
        "cmyk": "100/90/10/50",
        "rgb": "19/41/75",
        "hex": "#13294B",
        "variants": [],
    },
    {
        "name": "Alma Mater",
        "var": "il-alma-mater",
        "pms": "661C",
        "cmyk": "100/85/15/7",
        "rgb": "30/56/119",
        "hex": "#1E3877",
        "variants": [
            {"hex": "#4D69A0", "var": "il-alma-mater-1"},
            {"hex": "#849BC1", "var": "il-alma-mater-2"},
            {"hex": "#AFC7DB", "var": "il-alma-mater-3"},
        ],
    },
    {
        "name": "Industrial Blue",
        "var": "il-industrial-blue",
        "pms": "285C",
        "cmyk": "90/48/0/0",
        "rgb": "29/88/167",
        "hex": "#1D58A7",
        "variants": [
            {"hex": "#5783BC", "var": "il-industrial-blue-1"},
            {"hex": "#90AED5", "var": "il-industrial-blue-2"},
            {"hex": "#CAD9EF", "var": "il-industrial-blue-3"},
        ],
    },
    {
        "name": "Arches Blue",
        "var": "il-arches-blue",
        "pms": "298C",
        "cmyk": "70/5/2/0",
        "rgb": "0/159/212",
        "hex": "#009FD4",
        "variants": [
            {"hex": "#7FC3E1", "var": "il-arches-blue-1"},
            {"hex": "#A6D7EB", "var": "il-arches-blue-2"},
            {"hex": "#D2EBF5", "var": "il-arches-blue-3"},
        ],
    },
    {
        "name": "Cloud",
        "var": "il-cloud",
        "style": "light",
        "pms": "COOL GRAY 1C",
        "cmyk": "3/2/2/1",
        "rgb": "248/250/252",
        "hex": "#F8FAFC",
        "variants": [
            {"hex": "#E8E9EB", "var": "il-cloud-1"},
            {"hex": "#DDDEDE", "var": "il-cloud-2"},
            {"hex": "#D2D2D2", "var": "il-cloud-3"},
        ],
    },
    {
        "name": "Heritage Orange",
        "var": "il-heritage-orange",
        "pms": "715C",
        "cmyk": "0/57/94/00",
        "rgb": "245/130/30",
        "hex": "#F5821E",
        "variants": [
            {"hex": "#E56E15", "var": "il-heritage-orange-1"},
            {"hex": "#CE5E11", "var": "il-heritage-orange-2"},
            {"hex": "#B74D04", "var": "il-heritage-orange-3"},
        ],
    },
];
